### ISSUE TITLE
runtime: systemstack should align stack on 16-bytes

### ISSUE THREAD

**Issue by 4ad** [4ad/go.arm64#100]
All stacks must be 16-byte aligned, but newsysmon gets called with SP%16=8.

**Comment by davecheney** [comment]
:crying:

**Comment by davecheney** [comment]
Doesn't 6g have this restriction, amd64 stacks and function calls should be
16 byte aligned, yes ?

**Comment by minux** [comment]
AMD64 ABI has this requirement, but we pretty much disregard it.

In places where this truly matter we align the stack pointer before calling
external code that expect proper SP alignment.

**Comment by 4ad** [comment]
Liblink properly aligns everything if we do the right thing (e.g. have proper framesizes), it fails only for $0 functions which modify the stack pointer themselves.

It's trivial to fix all these places, though I am not sure how that impacts stack traces. Can gotraceback deal with this?

**Comment by minux** [comment]
I don't think gotraceback can deal with manually aligned stacks. That's why
we only align the stack before calling external code (e.g. windows
"syscalls").

**Comment by 4ad** [comment]
This might be a problem then. I don't think the fix is too hard though.

**Comment by minux** [comment]
I mean, if liblink aligns the stack frame by adjusting frame size, then
there is
no problems for gotraceback. (however, adjusting the frame size might have
other issues for hand written assembly functions)

but if we adjust SP manully by SUB and AND, then gotraceback can't handle
this case.

We control the Go ABI, do we need to maintain proper stack alignment
internally?
I think the only case where this matters is before we call foreign
functions (e.g.
syscall and cgo). Linux syscall shouldn't care about user stack so we only
need
to maintain correct stack alignment for cgocalls.

**Comment by 4ad** [comment]
Yes, you get a SIGBUS if the stack is not aligned.

**Comment by 4ad** [comment]
(Not only stack, but any kind of indirect reference through SP too, e.g. 16(SP) crashes if SP%16=8).

**Comment by minux** [comment]
OK, so we need to make cmd/7g adjust the frame size 8 mod 16 and
also make liblink give an error if total frame size is not aligned to 16
bytes?

**Comment by 4ad** [comment]
Not really. I think everything is mostly correct now, apart from assembly functions that modify the stack pointer manually in an incorrect way. The way liblink works now is that if you ask for a non-aligned frame size, it will align it for you by making it bigger. In other words, it will always generate correct code.

I think this is good and better than if we just require the user of liblink (assemblers, compiler) to specify correct framesize, because the passed framesize, or the framesize set in assembly always matches what the human user would expect, so it's easy to verify, and also makes go vet just work without significant changes.

**Comment by minux** [comment]
I think this has been fully fixed, no?

**Comment by 4ad** [comment]
I think so, yes.
