### ISSUE TITLE
7g: accessing global variables fails 

### ISSUE THREAD

**Issue by mwhudson** [4ad/go.arm64#13]
```
mwhudson@narsil:shared-lib-stuff$ cat gvar64.go 
package p

var i int64 = 1111111

func g() int64 {
    return i
}
mwhudson@narsil:shared-lib-stuff$ GOARCH=arm64 go tool 7g gvar64.go
00004 (gvar64.go:6) MOV "".i+0(SB),R9
00004 (gvar64.go:6) MOV "".i+0(SB),R9
gvar64.go:7: illegal combination 00004 (gvar64.go:6)    MOV "".i+0(SB),R9 ADDR NONE     = 0 REG, 7 14
mwhudson@narsil:shared-lib-stuff$ cat gvar32.go 
package p

var i int32 = 1111111

func g() int32 {
    return i
}
mwhudson@narsil:shared-lib-stuff$ GOARCH=arm64 go tool 7g gvar32.go
gvar32.go:7: address constant needs DWORD
00028 (<unknown line number>)   WORD    ,"".i+0(SB)
```

I think the gvar32.go problem is more or less the same as issue 10.  The problem with the 64 bit variable seems to be a missing entry from optab but maybe not...

**Comment by minux** [comment]
Yes, this is just another symptom of #10 (basically these two
are the same problem)

I think the problem is in liblink/asm7.c:/^addpool

**Comment by mwhudson** [comment]
FWIW, the former problem is present in ken-cc as well when one uses 7l -u (which more or less makes the behaviour of its aclass match that of liblink's).

```
mwhudson@narsil:shared-lib-stuff$ cat gvar64.c 
long long foo = 11;

int _main() {
    return foo;
}
mwhudson@narsil:shared-lib-stuff$ 7c gvar64.c
mwhudson@narsil:shared-lib-stuff$ 7l -u gvar64.7
_main: illegal combination MOV ADDR NONE REG
(3) MOV foo+0(SB),R0
_main: illegal combination MOV ADDR NONE REG
(3) MOV foo+0(SB),R0
mwhudson@narsil:shared-lib-stuff$ cat gvar64.c 
```

**Comment by 4ad** [comment]
> the former problem is present in ken-cc as well when one uses 7l -u

The -u flag is not supposed to work though.

> I think the problem is in liblink/asm7.c:/^addpool

I think the problem is in aclass. When converting to liblink I made more things use C_ADDR when something else should be used instead. I'll investigate.

**Comment by mwhudson** [comment]
Aram Hăvărneanu notifications@github.com writes:

> > the former problem is present in ken-cc as well when one uses 7l -u
> 
> The -u flag is not supposed to work though.

Well, OK, but what I guess I really meant here is that the style of
accessing 64-bit data via relocations, which at least 6g also seems to
use on this sort of construct, is broken in ken-cc 7l too, so this is
not a bug introduced by the ken-cc -> go transition.  Accessing 32-bit
data and using 7l -u fails in a different way, more like the other
problem:

> > I think the problem is in liblink/asm7.c:/^addpool
> 
> I think the problem is in aclass. When converting to liblink I made more things use C_ADDR when something else should be used instead. I'll investigate.

Cheers,
mwh

**Comment by 4ad** [comment]
There were multiple problems here and they have been fixed.
