### ISSUE TITLE
cmd/7l: external linking support

### ISSUE THREAD

**Issue by minux** [4ad/go.arm64#130]

**Comment by mwhudson** [comment]
Given I have my head in the linker currently, I could have a go at this.  Do you think it's something that could be reasonably implemented given the current state of things, or would it be futile for the moment?

**Comment by minux** [comment]
I think it's reasonable to start implementing external linking at this
stage.
We're pretty close to all.bash passing.

**Comment by minux** [comment]
Actually, external linking development can start even earlier.
Once you have a hello world program working, it could start.

Just generate a go.o relocatable ELF and use ld to do the final
linking. Once ld could produce working binary, it's mostly done.

And then we will need cgo support.

**Comment by mwhudson** [comment]
OK, I had a quick hack, see branch I pushed. Something goes wrong with the
dwarf relocs (and I don't understand the dwarf bits of the linker at all
yet) but it you pass -w it makes a binary. Which segfaults in osinit -
possibly just after the first syscall, although I don't know if that is
relevant. The fact that the smallest possible go program is quite large
strikes again - maybe I'll try with the mini runtime tomorrow.

sent from my phone, please excuse brevity
