### ISSUE TITLE
build failure since a7ba86c75f4c (implement Link in terms of Linkat)

### ISSUE THREAD

**Issue by frobware** [4ad/go.arm64#133]
I cloned the tree:

aim@x1c:/tmp
: git clone http://github.com/4ad/go
Cloning into 'go'...
remote: Counting objects: 194894, done.
remote: Compressing objects: 100% (267/267), done.
remote: Total 194894 (delta 220), reused 91 (delta 68)
Receiving objects: 100% (194894/194894), 54.06 MiB | 2.93 MiB/s, done.
Resolving deltas: 100% (161506/161506), done.
Checking connectivity... done.
aim@x1c:/tmp
: cd go
aim@x1c:/tmp/go
: cd src
aim@x1c:/tmp/go/src
: GOARCH=arm64 ./make.

[ elided]

trings
strconv
bufio
sort
container/heap
encoding/base64
syscall
/tmp/go/src/syscall/syscall_linux.go:37: undefined: Linkat
/tmp/go/src/syscall/syscall_linux.go:869: undefined: readlinkat
/tmp/go/src/syscall/syscall_linux.go:903: undefined: symlinkat
/tmp/go/src/syscall/zsyscall_linux_amd64.go:204: Chmod redeclared in this block
        previous declaration at /tmp/go/src/syscall/syscall_linux.go:824
/tmp/go/src/syscall/zsyscall_linux_amd64.go:246: Creat redeclared in this block
        previous declaration at /tmp/go/src/syscall/syscall_linux.go:22
/tmp/go/src/syscall/zsyscall_linux_amd64.go:635: Link redeclared in this block
        previous declaration at /tmp/go/src/syscall/syscall_linux.go:36
/tmp/go/src/syscall/zsyscall_linux_amd64.go:696: Mknod redeclared in this block
        previous declaration at /tmp/go/src/syscall/syscall_linux.go:857
/tmp/go/src/syscall/zsyscall_linux_amd64.go:797: Readlink redeclared in this block
        previous declaration at /tmp/go/src/syscall/syscall_linux.go:868
/tmp/go/src/syscall/zsyscall_linux_amd64.go:842: Rename redeclared in this block
        previous declaration at /tmp/go/src/syscall/syscall_linux.go:875
/tmp/go/src/syscall/zsyscall_linux_amd64.go:987: Symlink redeclared in this block
        previous declaration at /tmp/go/src/syscall/syscall_linux.go:902
/tmp/go/src/syscall/syscall_linux.go:903: too many errors
go tool dist: FAILED: /tmp/go/pkg/tool/linux_amd64/6g -pack -o /tmp/go-tool-dist-764739828/_go_.a -p syscall /tmp/go/src/syscall/env_unix.go /tmp/go/src/syscall/exec_linux.go /tmp/go/src/syscall/exec_unix.go /tmp/go/src/syscall/flock.go /tmp/go/src/syscall/lsf_linux.go /tmp/go/src/syscall/netlink_linux.go /tmp/go/src/syscall/race0.go /tmp/go/src/syscall/sockcmsg_linux.go /tmp/go/src/syscall/sockcmsg_unix.go /tmp/go/src/syscall/str.go /tmp/go/src/syscall/syscall.go /tmp/go/src/syscall/syscall_linux.go /tmp/go/src/syscall/syscall_linux_amd64.go /tmp/go/src/syscall/syscall_unix.go /tmp/go/src/syscall/zerrors_linux_amd64.go /tmp/go/src/syscall/zsyscall_linux_amd64.go /tmp/go/src/syscall/zsysnum_linux_amd64.go /tmp/go/src/syscall/ztypes_linux_amd64.go

I was able to build and run 'hello world' earlier today \o/ with b933b98029c8b5357d50820c5547e164876ea75e

**Comment by 4ad** [comment]
Yes, known issue. Only arm and arm64 builds are working right now. 386, amd64 and ppc64 are broken. Someone has to regenerate zsyscall_linux_amd64.go from an amd64 machine.

**Comment by 4ad** [comment]
Basically 

```
cd go/src/syscall
./mksyscall.pl syscall_linux.go syscall_linux_amd64.go |gofmt >zsyscall_linux_amd64.go
```

**Comment by frobware** [comment]
Ah, I was s/amd/arm/. Builds OK now.

**Comment by minux** [comment]
I've fixed the build errors on other platforms in https://github.com/minux/go-arm64/commit/bfdc81b7fe6f38f343843458ce346e353a5ce23e

**Comment by 4ad** [comment]
I believe this is fixed.
