### ISSUE TITLE
arm64 native build

### ISSUE THREAD

**Issue by ikitayama** [4ad/go.arm64#137]
I am wondering if either branch, dev.arm64 or mwhudson-bits can be checked out for
native build.

**Comment by minux** [comment]
the dev.arm64 can be native built, and that's the main development branch.

**Comment by ikitayama** [comment]
Here's what I got using that branch:
$ ./all.bash 

##### Building Go bootstrap tool.

cmd/dist
ERROR: Cannot find /home/itaru.kitayama/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
./make.bash: line 124: /home/itaru.kitayama/go1.4/bin/go: No such file or directory

**Comment by minux** [comment]
You need a working Go 1.4 at $HOME/go1.4 to build.

First build Go 1.4 with GOARCH=arm GOHOSTARCH=arm CGO_ENABLED=0

**Comment by ikitayama** [comment]
In the src dir,
$ CC='arm-linux-gnu-gcc -static' GOARCH=7 GOHOSTARCH=arm CGO_ENABLED=0 ./make.bash

it still looks for Go 1.4.

**Comment by minux** [comment]
You need to have Go 1.4 available at $HOME/go1.4.

There is no way to get around that requirement.

See https://golang.org/s/go15bootstrap for details on how to bootstrap Go 1.5.

**Comment by 4ad** [comment]
Working as intended.
