### ISSUE TITLE
7a/liblink: compare-with-immediate 0 misassembled

### ISSUE THREAD

**Issue by mwhudson** [4ad/go.arm64#14]
"CMP $0,R13" in a .s file ends up being assembled as:

  1c:   eb2001bf    cmp x13, w0, uxtb

which is not at all the right thing (gnu as assembles "cmp x13, #0" as "f10001bf    cmp x13, #0x0")

**Comment by mwhudson** [comment]
Ah, ken-cc assembles this as "eb1f01bf  cmp x13, xzr", which is not so far from what liblink is producing...

**Comment by mwhudson** [comment]
Well, I know why ken-cc and liblink produce different results: when assembling this instruction the value of rf at https://github.com/4ad/go/blob/dev.arm64/src/liblink/asm7.c#L1729 is 32 whereas in the equivalent time and place in ken-cc it's 31.  No idea why though.

**Comment by mwhudson** [comment]
It turns out ken-cc sets the reg value of a constant-zero Adr to REGZERO when **reading the Adr from the .7 file**:

```
https://code.google.com/p/ken-cc/source/browse/src/cmd/7l/obj.c#293
```

I guess with liblink there is no .7 file and so this tweaking doesn't happen.  Maybe span7 can do it?  I don't _think_ zaddr is doing any other trickery that needs to be replicated.

**Comment by davecheney** [comment]
:scream:

**Comment by mwhudson** [comment]
Pushed a fix.  Didn't think very hard about names or formatting.

**Comment by 4ad** [comment]
Thanks for debugging this.

**Comment by 4ad** [comment]
I'm confused about this, why should a $0 constant have a->reg=REGZERO instead of a->reg=NREG, like $42 does. aclass only cares about its value when emitting C_ZCON (at least in the current code). How exactly is the broken code generated?
