### ISSUE TITLE
cmd/internal/ld: portable registerizer generates invalid code

### ISSUE THREAD

**Issue by 4ad** [4ad/go.arm64#145]
Surely this is bad:

```
GOARCH=arm64 go tool 7g -S -o /home/aram/tmp/timediv.7 /home/aram/tmp/timediv.go
"".timediv t=1 nosplit size=416 value=0 args=0x20 locals=0x0 leaf
    0x0000 00000 (/home/aram/tmp/timediv.go:4)  TEXT    "".timediv(SB),4,$-8-32
    0x0000 00000 (/home/aram/tmp/timediv.go:4)  MOVD    "".rem+16(FP),R0
    0x0004 00004 (/home/aram/tmp/timediv.go:4)  MOVW    "".div+8(FP),R0
    0x0008 00008 (/home/aram/tmp/timediv.go:4)  MOVD    "".v(FP),R0
```

**Comment by davecheney** [comment]
is that it ? where is the RET ?

**Comment by 4ad** [comment]
Well, no, that's only the beginning of the function, but it's already wrong, using the same register for all arguments is bad.

**Comment by davecheney** [comment]
omg, i missed that. /facepalm

**Comment by 4ad** [comment]
Also, further down R0 is not even used, it's overwritten with ZR.

**Comment by 4ad** [comment]
Fixed I think, pushing fix soon.

**Comment by minux** [comment]
I'm wondering what's the cause for this?

**Comment by minux** [comment]
OK. I see. the ppc64 code is correct, as R0 is the zero register,
and shouldn't be assigned.
