### ISSUE TITLE
cmd/7g: compiler generates incorrect code for large-offset indirects

### ISSUE THREAD

**Issue by davecheney** [4ad/go.arm64#22]
Ignore the `DWORD` errors, 

```
00616 (/home/dfc/go.arm64/src/runtime/cpuprof.go:158)   MOVBU   R10,3211324(R9)
00684 (/home/dfc/go.arm64/src/runtime/cpuprof.go:160)   MOVBU   R10,3211325(R9)
00716 (/home/dfc/go.arm64/src/runtime/cpuprof.go:161)   MOVBU   R10,3211326(R9)
01384 (<unknown line number>)   DWORD   ,$2162728(R9)
01064 (<unknown line number>)   DWORD   ,$2162728(R9)
/home/dfc/go.arm64/src/runtime/alg.go:1: illegal combination 00616 (/home/dfc/go.arm64/src/runtime/cpuprof.go:158)      MOVBU   R10,3211324(R9) REG NONE= 0 LOREG, 14 7
/home/dfc/go.arm64/src/runtime/alg.go:1: illegal combination 00684 (/home/dfc/go.arm64/src/runtime/cpuprof.go:160)      MOVBU   R10,3211325(R9) REG NONE= 0 LOREG, 14 7
/home/dfc/go.arm64/src/runtime/alg.go:1: illegal combination 00716 (/home/dfc/go.arm64/src/runtime/cpuprof.go:161)      MOVBU   R10,3211326(R9) REG NONE= 0 LOREG, 14 7
```

**Comment by davecheney** [comment]
Simple repo

```
package x

func f() {
        q := new(struct {
                hash [1<<10]int
                x bool
        })
        q.x = false
        println(q.x)
}
```

**Comment by davecheney** [comment]
Looks like it's only affecting moves to boolean or uint8 struct members, my guess is that for uint16 and above 7g encodes this as a move of a whole word.

**Comment by davecheney** [comment]
And, only affecting stores above an offset of 4096.

**Comment by mwhudson** [comment]
FWIW, 7c seems to generate different code for accessing fields more than 4096 bytes away from the base (irrespective of field size, which is a bit imperfect).

I think the fix for this is to have entries in the optab for MOVx to/from C_LOREG and handle these cases via a temporary register (this is what asm9.c does, search for "case 35:")

**Comment by 4ad** [comment]
We should make 7g generate code like 7c does.

**Comment by mwhudson** [comment]
Why?  Surely liblink is the place that should know about the sizes of immediate encodings?

**Comment by davecheney** [comment]
Awesome, thank you for fixing this.

So this change affects the constant pool, which then rolls through into the
instruction selection for the size of the immediate to be encoded. Yes?
