### ISSUE TITLE
7g: implicit interface methods generate invalid indirect call

### ISSUE THREAD

**Issue by mwhudson** [4ad/go.arm64#24]
Small reproducer:

```
package p

type I interface {
    F()
}
```

gives error:

```
00020 (<autogenerated>:1)   BL  ,R7
00020 (<autogenerated>:1)   BL  ,R7
<autogenerated>:1: illegal combination 00020 (<autogenerated>:1)    BL  ,R7 NONE        = 0 NONE        = 0 REG, 1 14
```

This looks very similar to the problem with an explicit indirect call fixed in d032caa4afe5296fd7bf126f3293e121556eea05 and I imagine the fix will be similar too.

**Comment by mwhudson** [comment]
This seems to fix it but somehow doesn't seem right:

``` diff
diff --git a/src/cmd/7g/ggen.c b/src/cmd/7g/ggen.c
index 948212c..17d9899 100644
--- a/src/cmd/7g/ggen.c
+++ b/src/cmd/7g/ggen.c
@@ -214,7 +214,10 @@ ginscall(Node *f, int proc)
                break;

        case 3: // normal call of c function pointer
-               gins(ABL, N, f);
+               nodreg(&reg, types[tptr], D_R0+REGENV);
+               gmove(f, &reg);
+               reg.op = OINDREG;
+               gins(ABL, N, &reg);
                break;

        case 1: // call in new proc (go)
```

**Comment by minux** [comment]
I think optab should add ABL NONE NONE C_REG entry.

**Comment by davecheney** [comment]
What is C_SBRA, section break reg address ?

**Comment by mwhudson** [comment]
"symbol branch" vs C_LBRA "label branch" was my guess, but no idea

**Comment by minux** [comment]
On Dec 17, 2014 7:32 PM, "Dave Cheney" notifications@github.com wrote:

> What is C_SBRA, section break reg address ?
> I think it means short branch, to targets near enough that it can be
> encoded in one branch instruction.

The opposite is LBRA, but as liblink layout one function at a time, most
don't bother to support that. Grep for "very large branches" in asm7.c. We
can enable that loop later.

However, the current cmd/ld couldn't handle very large jumps either. It
doesn't know how to generate thunks.

**Comment by mwhudson** [comment]
Minux Ma notifications@github.com writes:

> I think optab should add ABL NONE NONE C_REG entry.

Yes, I can't see why not.  Or C_ZOREG and C_REG could be compatible per
cmp().  Or the same thing?  I don't really see why they are different.

**Comment by 4ad** [comment]
On Thu, Dec 18, 2014 at 1:54 AM, Minux Ma notifications@github.com wrote:

> I think it means short branch, to targets near enough that it can be
> encoded in one branch instruction.

This is correct.

## 

Aram Hăvărneanu

**Comment by 4ad** [comment]
On Thu, Dec 18, 2014 at 9:48 AM, mwhudson notifications@github.com wrote:

> Or C_ZOREG and C_REG could be compatible per
> cmp(). Or the same thing? I don't really see why they are different.

I'm not sure what are you asking here. C_ZOREG and C_REG they both
"look" the same in assembly, but they mean very different things. Only
one form can be supported at the same time.

## 

Aram Hăvărneanu

**Comment by mwhudson** [comment]
Aram Hăvărneanu notifications@github.com writes:

> On Thu, Dec 18, 2014 at 9:48 AM, mwhudson notifications@github.com wrote:
> 
> > Or C_ZOREG and C_REG could be compatible per
> > cmp(). Or the same thing? I don't really see why they are different.
> 
> I'm not sure what are you asking here. C_ZOREG and C_REG they both
> "look" the same in assembly, but they mean very different things. Only
> one form can be supported at the same time.

Oh right.  So R1 is REG but 0(R1) is C_ZOREG?  Those are very different,
I agree!  It's only in the context of branches that one could possibly
confuse them...
