### ISSUE TITLE
7g: initializing a structure that takes between 4 and 128 dwords fails

### ISSUE THREAD

**Issue by mwhudson** [4ad/go.arm64#25]
For example:

``` shellsession
mwhudson@narsil:shared-lib-stuff$ cat duff.go
package p

type s struct {
    a [4]uintptr
}

func f() uintptr {
    var s s
    return s.a[0]
}
mwhudson@narsil:shared-lib-stuff$ GOARCH=arm64 go tool 7g duff.go
00024 (duff.go:8)   DUFFZERO    ,runtime.duffzero+496(APC)
duff.go:10: bad bra DUFFZERO
```

It's pretty easy to see which code is responsible, it's the q>= 4 case in ggen.c:clearfat.

**Comment by davecheney** [comment]
We should comment out that clearfat stuff (for the moment) it is really
subtle and breaks in bonkers ways. You can bodge it so that it always
defaults to the hard case and uses memclr.

**Comment by minux** [comment]
Clearfat obviously has its own problems, as it's still using 9g's register
convention.

But for this particular problem, I think it's liblink not being able to
handle calls into middle of a function.
