### ISSUE TITLE
cmd/7a: are post-indexed load/stores supported ?

### ISSUE THREAD

**Issue by davecheney** [4ad/go.arm64#39]
(gas style)

LDR X0, (X1), #4 

doesn't appear to be supported, i've tried

MOVB 1(R1), R0   // syntax error

and

MOVB $1(R1), R0 // illegal combination 00032 (/home/dfc/go.arm64/src/runtime/asm_arm64.s:35)       MOVB    $1(R1),R4 AACON NONE REG, 10 14

This would be nice to have for #38

**Comment by mwhudson** [comment]
It is supported, @4ad sent me a version of asm.pdf with all the addressing modes documented... I'll find it and forward it to you.

**Comment by 4ad** [comment]
It's supported:

```
TEXT foo(SB),7,$-8
    MOV (R1)32!,R2
    MOV R3,16(R4)!
    RETURN
```

The first is post-index, the second is pre-index.

**Comment by davecheney** [comment]
Got it,I'll fix my memeq branch tomorrow. 

I'm working on sys_linux_arm64.s as well

**Comment by 4ad** [comment]
Please use these sparingly, they are very hard to reason about. A good use case (which we already make use of) si LR-saving. I can think of a few other cases where this is warranted.

**Comment by davecheney** [comment]
Sure. In this case I'm trying to translate memeq/stringeq from 5g with as little change as possible.

**Comment by 4ad** [comment]
In general you should use amd64 and ppc64 code as reference, 32-bit arm is a very poor fit.

**Comment by minux** [comment]
post-index also fits nicely with duffzero and duffcopy.

ppc64 only has pre-index addressing mode, so before calling duffzero and
duffcopy
you will need to pre-adjust the pointers (duffcopy is esp. twisted, the
input is source
pointer - 8, and the difference between the dst and src pointers). not fun.
(or very fun
depending on your view point. ;-))

the 5a assembler uses mnemonic suffixes (.P and .W) to set addressing mode,
i like
7a's way better.
