### ISSUE TITLE
cmd/liblink: MOV $4294967295, R misassembled

### ISSUE THREAD

**Issue by 4ad** [4ad/go.arm64#67]
```
0x0000 00000 (a.s:2)    TEXT    foo+0(SB),7,$-8--2147483648
0x0000 00000 (a.s:2)    MOV $-1,R7
0x0004 00004 (a.s:3)    MOV $4294967295,R7
0x0008 00008 (<unknown line number>)    RET ,0(R30)
0x0000 07 00 80 92 e7 7f 00 b2 c0 03 5f d6 00 00 00 00  .........._.....
rel 8+0 t=7 +0
```

e7 7f 00 b2 is an undefined instruction. Note that 4294967295 is 0xffffffff.

**Comment by davecheney** [comment]
Not to mention -2147483648 is also 0xffffffff

**Comment by 4ad** [comment]
Yeah, it is. There's no problem with that, liblink (correctly) sets it to 0x80000000 if we don't provide an argsize. The print uses a signed interpretation. Same print happens on arm and ppc64.

**Comment by 4ad** [comment]
args=0xffffffff80000000 locals=0xfffffffffffffff8

This is good.
