### ISSUE TITLE
runtime: implement 64-bit atomics

### ISSUE THREAD

**Issue by 4ad** [4ad/go.arm64#72]
Actually 64-bit atomics are implemented in sync/atomic, but in runtime there's a really lame fallback (in Go even!) that uses 32-bit CAS to implement all the other atomics. Gross.

Let's get rid of that.

**Comment by davecheney** [comment]
Yeah. I copied that nastiness from 5g. I agree it can be done better.

**Comment by davecheney** [comment]
It turns out that because of #78 we don't get very far into the process before things go south. 

Without 64bit atomics we need to use `systemstack` and closures to fake a 64bit atomic.

All this goes away if we just use proper 64bit atomics, so lets do that.
