### ISSUE TITLE
computing address of interior field via pointer broken

### ISSUE THREAD

**Issue by mwhudson** [4ad/go.arm64#90]
The summary is a bit of a guess I suppose.  This is what currently kills runtime initialization.

Compiling this code:

``` go
package mheap

type mspan struct {
    foo uintptr
    bar uintptr
}

type mheap struct {
    free [10]mspan
}

func mHeap_Init(h *mheap, j int32) {
    mSpanList_Init(&h.free[j])
}

func mSpanList_Init(s *mspan) {
    s.foo = 0
}
```

Results in this:

```
    0x0000 00000 (mheap.go:12)  TEXT    "".mHeap_Init+0(SB),$24-16
    0x0000 00000 (mheap.go:12)  MOV R30,-32(R31)!
    0x0004 00004 (mheap.go:12)  FUNCDATA    $0,gclocals·cd30d2bcfdea04ed7c49639580b4bd08+0(SB)
    0x0004 00004 (mheap.go:12)  FUNCDATA    $1,gclocals·3280bececceccd33cb74587feedb1f9f+0(SB)
    0x0004 00004 (mheap.go:13)  MOV "".h+0(FP),R0
    0x0008 00008 (mheap.go:13)  CMP R0,R31,
    0x000c 00012 (mheap.go:13)  BNE ,00014(BRANCH)
    0x0010 00016 (mheap.go:13)  MOV R0,0(R31)
    0x0014 00020 (mheap.go:13)  MOV $0,R1
    0x0018 00024 (mheap.go:13)  MOV R1,R1
    0x001c 00028 (mheap.go:13)  MOVW    "".j+8(FP),R0
    0x0020 00032 (mheap.go:13)  MOVW    R0,R2
    0x0024 00036 (mheap.go:13)  MOV R2,"".autotmp_0000-8(SP)
    0x0028 00040 (mheap.go:13)  MOV "".autotmp_0000-8(SP),R0
    0x002c 00044 (mheap.go:13)  MOV R0,R0
    0x0030 00048 (mheap.go:13)  MOV $16,R2
    0x0034 00052 (mheap.go:13)  UMULL   R2,R0
    0x0038 00056 (mheap.go:13)  ADD R0,R1
    0x003c 00060 (mheap.go:13)  MOV R1,8(R31)
    0x0040 00064 (mheap.go:13)  PCDATA  $0,$0
    0x0040 00064 (mheap.go:13)  BL  ,"".mSpanList_Init+0(PC)
    0x0044 00068 (mheap.go:14)  MOV (R31)32!,R30
    0x0048 00072 (mheap.go:14)  RET ,0(R30)
```

Chasing this through, the brokenness is that the UMULL at offset 0x34 stomps over R0, which contains h.  Maybe it's supposed to write to R1?

**Comment by mwhudson** [comment]
Hm no, R0 is stomped before that.  Could this be some kind of liveness problem?

**Comment by 4ad** [comment]
```
MOV $0,R1
```

I think this should be `MOV R0, R1`. Perhaps it's encoded as `MOV $0(R0),R1` and aclass is screwing us again. Just a guess.

**Comment by mwhudson** [comment]
Has a sort of plausible ring to it (I certainly can't see why putting 0 in R1 would make sense).

**Comment by mwhudson** [comment]
Can we avoid using register 0 entirely?  I tried changing REGMIN to 1 but that didn't seem to make any difference?

(I think we're about to run into an analogous problem to https://github.com/golang/go/issues/9766 which I just found, except that as well as printing the instruction wrong we're also assembling it wrong)

**Comment by mwhudson** [comment]
Ah no, changing REGMIN does work but you have to fight a bit to get everything to rebuild and notice it.  It doesn't fix anything though, the problem instruction now prints as "MOV    $8(R1),R2" but assembles as "movz x2, #0x8" (and should be add r2, r1, #0x8).

**Comment by mwhudson** [comment]
Ah, so I had blanked on the difference between "8(R1)" and "$8(R1)" -- the $ prefix means the expression computes the effective address of the memory reference that follows rather than the contents of the memory... so this means whacking at aclass again :(

**Comment by mwhudson** [comment]
I tried to add a "C_EFFECTIVEADDRESS" for aclass to return in this case, but it all gets tangled up in what to do when the offset is 0 and zero register confusion and the commit i just pushed makes runtime initialization hang earlier than it did before :(

**Comment by mwhudson** [comment]
PS: I hate everything.

**Comment by 4ad** [comment]
All we need to do is make $0 use NREG, then we could use a->reg for every D_CONST without any ambiguity.

$0 constants are set to REGZERO (instead of NREG) in span7. We can delete that, but then instructions get misassembled. We need to fix that before we can fix this.

**Comment by 4ad** [comment]
Actually we can't use NREG for $0, because C_ZCON matches C_REG with REGZERO in optab, and asmout cases really expect to use a->reg. We need a better way.

**Comment by davecheney** [comment]
Is it possible to ensure regzero is never used by 7g, the we can handle the small number of .s cases manually?

**Comment by 4ad** [comment]
No, not really. It's quite fundamental. E.g. there is only ADD $42, ZR, R to implement small moves; ADD $42, $0, R doesn't exist.

I have a fix here, but it hits another bug. C_LACON and C_AACON expect always to operate on SP, not other register. Fixing that now.

**Comment by davecheney** [comment]
Ok, I might have been going in the wrong direction.

I think I get confused between R0, the register, $0 th immediate constant and zr the register that contains 0

**Comment by minux** [comment]
Is this still broken?

**Comment by 4ad** [comment]
No, it works. But I'm not very happy with the fix.
